<?php

/* Fields and Constant */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

if ( !class_exists( 'Mezar_Qv_Pro_Fields' ) ) {

	class Mezar_Qv_Pro_Fields {

		public function __construct() {}

		public static function mezar_qv_fields () {
			$fields = array(
					array(
						'uid' => 'mezar_qv_button_label',
						'label' => 'QuickView Button Label',
						'section' => 'mezar_qv_third_section',
						'type' => 'text',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Leave it empty if you want to display the icon only',
						'default' => 'Quick View'
					),
					array(
						'uid' => 'mezar_qv_button_font_size',
						'label' => 'Font Size (text)',
						'section' => 'mezar_qv_third_section',
						'type' => 'number',
						'helper' => '(px)',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Text Size',
						'default' => 14,
					),
					array(
						'uid' => 'mezar_qv_button_icon_size',
						'label' => 'Font Size (icon)',
						'section' => 'mezar_qv_third_section',
						'type' => 'number',
						'helper' => '(px)',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Icon Size',
						'default' => 14,
					),
					array(
						'uid' => 'mezar_qv_button_position',
						'label' => 'QuickView Position',
						'section' => 'mezar_qv_third_section',
						'type' => 'select',
						'options' => array(
							'before_cart_button' => 'Before "Add to Bascket" Button',
							'after_cart_button' => 'After "Add to Bascket" Button',
							'after_price' => 'After Price',
							'after_rating' => 'After Rating',
							'after_title' => 'After Title',
							'before_title' => 'Before Title',
						),
						'placeholder' => '',
						'helper' => 'Position of QuickView Button',
						'supplemental' => '(default: Before "Add to Cart" Button)',
						'default' => 'before_cart_button'
					),
					array(
						'uid' => 'mezar_qv_button_dots',
						'label' => 'Show dots',
						'section' => 'mezar_qv_fourth_section',
						'type' => 'select',
						'options' => array(
							'true' => 'true',
							'false' => 'false',
						),
						'placeholder' => '',
						'helper' => 'Show Indicators',
						'supplemental' => '',
						'default' => 'false'
					),
					array(
						'uid' => 'mezar_qv_button_dots_size',
						'label' => 'Dots Size',
						'section' => 'mezar_qv_fourth_section',
						'type' => 'select',
						'type' => 'number',
						'helper' => '(px)',
						'placeholder' => '',
						'supplemental' => '',
						'default' => '30'
					),
					array(
						'uid' => 'mezar_qv_button_arrow',
						'label' => 'Show arrows',
						'section' => 'mezar_qv_fourth_section',
						'type' => 'select',
						'options' => array(
							'true' => 'true',
							'false' => 'false',
						),
						'placeholder' => '',
						'helper' => 'Show Arrows for Sliding',
						'supplemental' => '',
						'default' => 'true'
					),
					array(
						'uid' => 'mezar_qv_draggable',
						'label' => 'Draggable',
						'section' => 'mezar_qv_fourth_section',
						'type' => 'select',
						'options' => array(
							'true' => 'true',
							'false' => 'false',
						),
						'placeholder' => '',
						'helper' => 'Enable Sliding With Mouse Dragging',
						'supplemental' => '',
						'default' => 'true'
					),
					array(
						'uid' => 'mezar_qv_autoplay',
						'label' => 'Autoplay',
						'section' => 'mezar_qv_fourth_section',
						'type' => 'select',
						'options' => array(
							'true' => 'true',
							'false' => 'false',
						),
						'placeholder' => '',
						'helper' => 'Enable Autoplay for Sliding',
						'supplemental' => '',
						'default' => 'false'
					),
					array(
						'uid' => 'mezar_qv_fade',
						'label' => 'Fade',
						'section' => 'mezar_qv_fourth_section',
						'type' => 'select',
						'options' => array(
							'true' => 'true',
							'false' => 'false',
						),
						'placeholder' => '',
						'helper' => 'Enable Fade',
						'supplemental' => 'if you choose "false", it will slide with default animation ',
						'default' => 'true'
					),
					array(
						'uid' => 'mezar_qv_color_dots',
						'label' => 'Slider dots color',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Normal',
						'default' => '#0a0a0a',
					),
					array(
						'uid' => 'mezar_qv_color_normal',
						'label' => 'Button Text color (normal)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Normal',
						'default' => '#fff',
					),
					array(
						'uid' => 'mezar_qv_color_hover',
						'label' => 'Button color(hover)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Hover',
						'default' => '#0a0a0a',
					),
					array(
						'uid' => 'mezar_qv_bbg_color_normal',
						'label' => 'Button background color (normal)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Normal',
						'default' => '#0a0a0a',
					),
					array(
						'uid' => 'mezar_qv_bbg_color_hover',
						'label' => 'Button background color(hover)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Hover',
						'default' => '#fff',
					),
					array(
						'uid' => 'mezar_qv_bg_color',
						'label' => 'Container Color',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => '',
						'default' => '#fff',
					),
					array(
						'uid' => 'mezar_qv_bg_width',
						'label' => 'Width',
						'section' => 'mezar_qv_sixth_section',
						'type' => 'number',
						'helper' => '%',
						'options' => false,
						'placeholder' => '',
						'supplemental' => '',
						'default' => '100',
					),
					array(
						'uid' => 'mezar_qv_bg_height',
						'label' => 'height',
						'section' => 'mezar_qv_sixth_section',
						'type' => 'number',
						'helper' => 'px',
						'options' => false,
						'placeholder' => '',
						'supplemental' => '',
						'default' => '450',
					),
					array(
						'uid' => 'mezar_qv_cont_padd',
						'label' => 'Container Padding',
						'section' => 'mezar_qv_sixth_section',
						'type' => 'text',
						'helper' => 'Use any unit (px,%,vh,em...) ',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'top,right,bottom,left',
						'default' => '20px',
					),
					array(
						'uid' => 'mezar_qv_gallery',
						'label' => 'Gallery',
						'section' => 'mezar_qv_fifth_section',
						'type' => 'select',
						'helper' => '',
						'options' => array(
							'true' => 'true',
							'false' => 'false',
						),
						'placeholder' => '',
						'supplemental' => 'Enable gallery',
						'default' => 'true',
					),
					array(
						'uid' => 'mezar_qv_gallery_arrow',
						'label' => 'Show arrows',
						'section' => 'mezar_qv_fifth_section',
						'type' => 'select',
						'options' => array(
							'true' => 'true',
							'false' => 'false',
						),
						'placeholder' => '',
						'helper' => 'Show Arrows for gallery',
						'supplemental' => '',
						'default' => 'true'
					),
					array(
						'uid' => 'mezar_qv_slide_show',
						'label' => 'Slide to Show',
						'section' => 'mezar_qv_fifth_section',
						'type' => 'number',
						'helper' => 'Number of Element in one slide',
						'options' => false,
						'placeholder' => '',
						'supplemental' => '(Default: 3)',
						'default' => 3,
					),
					array(
						'uid' => 'mezar_qv_right_icon',
						'label' => 'Right Arrow',
						'section' => 'mezar_qv_first_section',
						'type' => 'igroup',
						'container' => 'mezar_qv_right_icon_container', 
						'helper' => '',
						'single' => 'radio',
						'options' => array(
							'fa-arrow-right' => '<i class="fa fa-arrow-right"></i>',
							'fa-arrow-circle-right' => '<i class="fa fa-arrow-circle-right"></i>',
							'fa-long-arrow-right' => '<i class="fa fa-long-arrow-right"></i>',
							'fa-arrow-circle-o-right' => '<i class="fa fa-arrow-circle-o-right"></i>',
							'fa-chevron-right' => '<i class="fa fa-chevron-right"></i>',
							'fa-hand-o-right' => '<i class="fa fa-hand-o-right"></i>',
							'fa-caret-right' => '<i class="fa fa-caret-right"></i>',
							'fa-chevron-circle-right' => '<i class="fa fa-chevron-circle-right"></i>',
							'fa-caret-square-o-right' => '<i class="fa fa-caret-square-o-right"></i>'
						),
						'placeholder' => '',
						'supplemental' => 'Right Arrow',
						'default' => 'fa-arrow-circle-right',
					),
					array(
						'uid' => 'mezar_qv_left_icon',
						'label' => 'Left Arrow',
						'section' => 'mezar_qv_first_section',
						'type' => 'igroup',
						'container' => 'mezar_qv_left_icon_container', 
						'helper' => '',
						'single' => 'radio',
						'options' => array(
							'fa-arrow-left' => '<i class="fa fa-arrow-left"></i>',
							'fa-arrow-circle-left' => '<i class="fa fa-arrow-circle-left"></i>',
							'fa-long-arrow-left' => '<i class="fa fa-long-arrow-left"></i>',
							'fa-arrow-circle-o-left' => '<i class="fa fa-arrow-circle-o-left"></i>',
							'fa-chevron-left' => '<i class="fa fa-chevron-left"></i>',
							'fa-hand-o-left' => '<i class="fa fa-hand-o-left"></i>',
							'fa-caret-left' => '<i class="fa fa-caret-left"></i>',
							'fa-chevron-circle-left' => '<i class="fa fa-chevron-circle-left"></i>',
							'fa-caret-square-o-left' => '<i class="fa fa-caret-square-o-left"></i>',
						),
						'placeholder' => '',
						'supplemental' => 'Left Arrow',
						'default' => 'fa-arrow-circle-left',
					),
					array(
						'uid' => 'mezar_qv_arrows_icon_color_normal',
						'label' => 'Arrows color (normal)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Normal',
						'default' => '#0a0a0a',
					),
					array(
						'uid' => 'mezar_qv_arrows_icon_color_hover',
						'label' => 'Arrows color (hover)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Hover',
						'default' => '#212121',
					),
					array(
						'uid' => 'mezar_qv_close_icon',
						'label' => 'Close',
						'section' => 'mezar_qv_first_section',
						'type' => 'igroup',
						'container' => 'mezar_qv_left_icon_container', 
						'helper' => '',
						'single' => 'radio',
						'options' => array(
							'fa-close' => '<i class="fa fa-close"></i>',
							'fa-window-close' => '<i class="fa fa-window-close"></i>',
							'fa-window-close-o' => '<i class="fa fa-window-close-o"></i>',
							'fa-times-circle' => '<i class="fa fa-times-circle"></i>',
							'fa-times-circle-o' => '<i class="fa fa-times-circle-o"></i>',
						),
						'placeholder' => '',
						'supplemental' => 'Close Icon',
						'default' => 'fa-close',
					),
					array(
						'uid' => 'mezar_qv_close_icon_color_normal',
						'label' => 'Close icon color (normal)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Normal',
						'default' => '#0a0a0a',
					),
					array(
						'uid' => 'mezar_qv_close_icon_color_hover',
						'label' => 'Close icon color (hover)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Hover',
						'default' => '#212121',
					),
					array(
						'uid' => 'mezar_qv_element_to_show',
						'label' => 'Show',
						'section' => 'mezar_qv_sixth_section',
						'type' => 'gcheckbox',
						'helper' => '',
						'options' => array(
							'title' => 'Title',
							'rating' => 'Rating',
							'price' => 'Price',
							'excerpt' => 'Description', 
							'add_to_cart' => 'Add To Cart',
							'meta' => 'Product Meta',
						),
						'placeholder' => '',
						'supplemental' => 'Elements to show inside the Container',
						'default' => array( 'title', 'rating', 'price', 'excerpt', 'add_to_cart', 'meta' ),
						'container' => 'mezar_qv_element_to_show_container'
					),
					array(
						'uid' => 'mezar_qv_icon_to_view',
						'label' => 'QuickView',
						'section' => 'mezar_qv_first_section',
						'type' => 'igroup',
						'helper' => '',
						'single' => 'radio',
						'options' => array(
							'fa-eye' => '<i class="fa fa-eye"></i>',
							'fa-compress' => '<i class="fa fa-compress"></i>',
							'fa-ellipsis-v' => '<i class="fa fa-ellipsis-v"></i>',
							'fa-expand' => '<i class="fa fa-expand"></i>',
							'fa-search' => '<i class="fa fa-search"></i>',
						),
						'placeholder' => '',
						'supplemental' => 'Quick View Icon',
						'default' => 'fa-eye',
						'container' => 'mezar_qv_left_icon_container'
					),
					array(
						'uid' => 'mezar_qv_icon_to_view_color_normal',
						'label' => 'QuickView icon color (normal)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Normal',
						'default' => '#fff',
					),
					array(
						'uid' => 'mezar_qv_icon_to_view_color_hover',
						'label' => 'QuickView icon color (hover)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Hover',
						'default' => '#0a0a0a',
					),
					array(
						'uid' => 'mezar_qv_animation',
						'label' => 'Choose Animation',
						'section' => 'mezar_qv_second_section',
						'type' => 'select',
						'helper' => 'Animation that will fire for displaying the modal',
						'options' => array(
							'mezar_qv_zoom' => 'Zoom-In-Out',
							'mezar_qv_fade' => 'Fade-In-Out',
							'mezar_qv_unfold' => 'Unfold-In-Out',
							'mezar_qv_slide_horiz' => 'Road Runner',
						),
						'placeholder' => '',
						'supplemental' => 'Choose animation',
						'default' => 'mezar_qv_zoom',
					),
					array(
						'uid' => 'mezar_qv_animation_time',
						'label' => 'Animation Duration',
						'section' => 'mezar_qv_second_section',
						'type' => 'text',
						'helper' => '(second)',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Duration In seconds',
						'default' => .4,
					),
					array(
						'uid' => 'mezar_qv_pagination',
						'label' => 'Enable Pagination',
						'section' => 'mezar_qv_eight_section',
						'type' => 'select',
						'options' => array(
							'true' => 'true',
							'false' => 'false',
						),
						'placeholder' => '',
						'helper' => 'Display pagination',
						'supplemental' => 'By Category',
						'default' => 'false',
					),
					array(
						'uid' => 'mezar_qv_pagination_arrows_size',
						'label' => 'Arrow Size',
						'section' => 'mezar_qv_eight_section',
						'type' => 'text',
						'helper' => '(px)',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Arrows Size',
						'default' => 20,
					),
					array(
						'uid' => 'mezar_qv_pagination_arrows_normal',
						'label' => 'Pagination Arrow color (normal)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Normal',
						'default' => '#fff',
					),
					array(
						'uid' => 'mezar_qv_pagination_arrows_hover',
						'label' => 'Pagination Arrow color (hover)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Hover',
						'default' => '#212121',
					),
					array(
						'uid' => 'mezar_qv_pagination_preloader_color',
						'label' => 'Pagination Preloader color',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => '',
						'default' => '#fff',
					),
					array(
						'uid' => 'mezar_qv_pagination_overlay',
						'label' => 'Pagination Overlay Color',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => '',
						'default' => '#fff',
					),
					array(
						'uid' => 'mezar_qv_shortcode_label',
						'label' => 'Shortcode',
						'section' => 'mezar_qv_third_section',
						'type' => 'label',
						'helper' => '',
						'text' => 'ShortCode that allow you to add quickview button anywhere
						in your theme. ex: "[mezar_qv_sc id="116"]" where "id" stand for your product id',
						'options' => false,
						'placeholder' => '',
						'supplemental' => '',
						'default' => "",
					),
					array(
						'uid' => 'mezar_qv_button_detail',
						'label' => 'Show Detail button',
						'section' => 'mezar_qv_sixth_section',
						'type' => 'select',
						'options' => array(
							'true' => 'true',
							'false' => 'false',
						),
						'placeholder' => '',
						'helper' => 'Enable Detail Button',
						'supplemental' => '',
						'default' => 'false'
					),
					array(
						'uid' => 'mezar_qv_button_detail_text',
						'label' => 'Detail Button Text',
						'section' => 'mezar_qv_sixth_section',
						'type' => 'text',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Text that will be shown from the detail button',
						'default' => 'View Detail',
					),
					array(
						'uid' => 'mezar_qv_button_detail_text_size',
						'label' => 'Detail Button Text Size',
						'section' => 'mezar_qv_sixth_section',
						'type' => 'text',
						'helper' => '(px)',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'The size of the text',
						'default' => 12,
					),
					array(
						'uid' => 'mezar_qv_preloader',
						'label' => 'Preloader',
						'section' => 'mezar_qv_second_section',
						'type' => 'select',
						'options' => array(
							'mezar-qv-spinner-loader5' => 'Spinner Dots 1',
							'mezar-qv-spinner-loader4' => 'Spinner Dots 2',
							'mezar-qv-spinner-loader3' => 'Spinner 1',
							'mezar-qv-spinner-loader2' => 'Spinner 2',
							'mezar-qv-loader-bar' => 'Bar',
						),
						'placeholder' => '',
						'helper' => 'Preloader That will be displayed when you click on quick view button',
						'supplemental' => '(default: Bar)',
						'default' => 'mezar-qv-loader-bar'
					),
					array(
						'uid' => 'mezar_qv_preloader_size',
						'label' => 'Preloader Size',
						'section' => 'mezar_qv_second_section',
						'type' => 'text',
						'helper' => 'px',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Each preloader with his own size',
						'default' => 'default',
					),
					array(
						'uid' => 'mezar_qv_preloader_color',
						'label' => 'Preloader Color',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Normal',
						'default' => '#fff',
					),
					array(
						'uid' => 'mezar_qv_detail_normal',
						'label' => 'Detail color (normal)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Normal',
						'default' => '#fff',
					),
					array(
						'uid' => 'mezar_qv_detail_hover',
						'label' => 'Detail color (hover)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Hover',
						'default' => '#0a0a0a',
					),
					array(
						'uid' => 'mezar_qv_detail_bg_normal',
						'label' => 'Detail Background color (normal)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Normal',
						'default' => '#0a0a0a',
					),
					array(
						'uid' => 'mezar_qv_detail_bg_hover',
						'label' => 'Detail Background color (hover)',
						'section' => 'mezar_qv_seventh_section',
						'type' => 'color',
						'helper' => '',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'Hover',
						'default' => '#fff',
					),
					array(
						'uid' => 'mezar_qv_detail_padd',
						'label' => 'Detail Padding',
						'section' => 'mezar_qv_sixth_section',
						'type' => 'text',
						'helper' => 'Use any unit (px,%,vh,em...) ',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'top,right,bottom,left',
						'default' => '6px 12px',
					),
					array(
						'uid' => 'mezar_qv_rtl',
						'label' => 'Direction',
						'section' => 'mezar_qv_sixth_section',
						'type' => 'select',
						'options' => array(
							'mezar-qv-rtl' => 'Right to left',
							'mezar-qv-ltr' => 'Left to right',
						),
						'placeholder' => '',
						'helper' => 'Choose the direction of your contents inside container',
						'supplemental' => '',
						'default' => 'mezar-qv-ltr'
					),
					array(
						'uid' => 'mezar_qv_image_container_size',
						'label' => 'Image container width',
						'section' => 'mezar_qv_sixth_section',
						'type' => 'text',
						'placeholder' => '',
						'helper' => 'You can use any unit (px,%,em ...)',
						'supplemental' => 'Enter the width of image container. default(50%)',
						'default' => '50%'
					),
					array(
						'uid' => 'mezar_qv_zoom',
						'label' => 'Enable Zoom',
						'section' => 'mezar_qv_ninth_section',
						'type' => 'select',
						'options' => array(
							'true' => 'true',
							'false' => 'false',
						),
						'placeholder' => '',
						'helper' => 'Enable image Zoom on hover',
						'supplemental' => '',
						'default' => 'false'
					),
					array(
						'uid' => 'mezar_qv_zoom_scale',
						'label' => 'Zoom Scale',
						'section' => 'mezar_qv_ninth_section',
						'type' => 'text',
						'helper' => 'the scale of zoom',
						'options' => false,
						'placeholder' => '',
						'supplemental' => 'if you choose number 2 the image will be zoomed 200%, if 1.5 it will be zoomed 150% etc.. (default:2)',
						'default' => '2',
					),
					
			);
			return $fields;
		}		

	}

	new Mezar_Qv_Pro_Fields();

}




?>